# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'current_event_details_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_current_event_details_widget(object):
    def setupUi(self, current_event_details_widget):
        current_event_details_widget.setObjectName("current_event_details_widget")
        current_event_details_widget.resize(357, 104)
        self.current_event_widget_vertical_layout = QtWidgets.QVBoxLayout(current_event_details_widget)
        self.current_event_widget_vertical_layout.setObjectName("current_event_widget_vertical_layout")
        self.token_target_frame = QtWidgets.QFrame(current_event_details_widget)
        self.token_target_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.token_target_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.token_target_frame.setObjectName("token_target_frame")
        self.token_target_frame_horizontal_layout = QtWidgets.QHBoxLayout(self.token_target_frame)
        self.token_target_frame_horizontal_layout.setObjectName("token_target_frame_horizontal_layout")
        self.token_target_frame_label = QtWidgets.QLabel(self.token_target_frame)
        self.token_target_frame_label.setObjectName("token_target_frame_label")
        self.token_target_frame_horizontal_layout.addWidget(self.token_target_frame_label)
        self.token_target_frame_input_lineedit = QtWidgets.QLineEdit(self.token_target_frame)
        self.token_target_frame_input_lineedit.setObjectName("token_target_frame_input_lineedit")
        self.token_target_frame_horizontal_layout.addWidget(self.token_target_frame_input_lineedit)
        self.current_event_widget_vertical_layout.addWidget(self.token_target_frame)
        self.current_event_current_tokens_label = QtWidgets.QLabel(current_event_details_widget)
        self.current_event_current_tokens_label.setObjectName("current_event_current_tokens_label")
        self.current_event_widget_vertical_layout.addWidget(self.current_event_current_tokens_label)
        self.current_event_target_tokens_per_day_label = QtWidgets.QLabel(current_event_details_widget)
        self.current_event_target_tokens_per_day_label.setObjectName("current_event_target_tokens_per_day_label")
        self.current_event_widget_vertical_layout.addWidget(self.current_event_target_tokens_per_day_label)

        self.retranslateUi(current_event_details_widget)
        QtCore.QMetaObject.connectSlotsByName(current_event_details_widget)

    def retranslateUi(self, current_event_details_widget):
        _translate = QtCore.QCoreApplication.translate
        current_event_details_widget.setWindowTitle(_translate("current_event_details_widget", "Form"))
        self.token_target_frame_label.setText(_translate("current_event_details_widget", "Enter target tokens:"))
        self.current_event_current_tokens_label.setText(_translate("current_event_details_widget", "Current tokens: "))
        self.current_event_target_tokens_per_day_label.setText(_translate("current_event_details_widget", "Tokens needed per day: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    current_event_details_widget = QtWidgets.QWidget()
    ui = Ui_current_event_details_widget()
    ui.setupUi(current_event_details_widget)
    current_event_details_widget.show()
    sys.exit(app.exec_())
