# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ShoppingCart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shopping_cart_widget(object):
    def setupUi(self, shopping_cart_widget):
        shopping_cart_widget.setObjectName("shopping_cart_widget")
        shopping_cart_widget.resize(400, 300)
        self.shopping_cart_widget_layout = QtWidgets.QGridLayout(shopping_cart_widget)
        self.shopping_cart_widget_layout.setObjectName("shopping_cart_widget_layout")
        self.shopping_cart_widget_scrollArea = QtWidgets.QScrollArea(shopping_cart_widget)
        self.shopping_cart_widget_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shopping_cart_widget_scrollArea.setWidgetResizable(True)
        self.shopping_cart_widget_scrollArea.setObjectName("shopping_cart_widget_scrollArea")
        self.shopping_cart_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.shopping_cart_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 280))
        self.shopping_cart_scrollAreaWidgetContents.setObjectName("shopping_cart_scrollAreaWidgetContents")
        self.shopping_cart_scrollAreaWidgetContents_verticalLayout = QtWidgets.QVBoxLayout(self.shopping_cart_scrollAreaWidgetContents)
        self.shopping_cart_scrollAreaWidgetContents_verticalLayout.setObjectName("shopping_cart_scrollAreaWidgetContents_verticalLayout")
        self.shopping_cart_widget_scrollArea.setWidget(self.shopping_cart_scrollAreaWidgetContents)
        self.shopping_cart_widget_layout.addWidget(self.shopping_cart_widget_scrollArea, 0, 0, 1, 1)

        self.retranslateUi(shopping_cart_widget)
        QtCore.QMetaObject.connectSlotsByName(shopping_cart_widget)

    def retranslateUi(self, shopping_cart_widget):
        _translate = QtCore.QCoreApplication.translate
        shopping_cart_widget.setWindowTitle(_translate("shopping_cart_widget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shopping_cart_widget = QtWidgets.QWidget()
    ui = Ui_shopping_cart_widget()
    ui.setupUi(shopping_cart_widget)
    shopping_cart_widget.show()
    sys.exit(app.exec_())
